spring.application.name=zooavito
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/zooavito
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.security.servlet.ServletWebSecurityAutoConfiguration,\
  org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
